### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by fumi-328** [fumi-328/danshari#18]
issueを作成いたしました。
ご確認の程よろしくお願いいたします。

---

### 実装予定の機能（MVP時点）
- [ ] LINEログイン機能
- [ ] 検索機能
- [ ] ユーザー全員の物一覧閲覧機能（未ログインでも閲覧可能）
- [ ] 断捨離する物の投稿機能（画像投稿含む,詳細の登録）
- [ ] 断捨離する物の編集機能
- [ ] 断捨離する物の削除機能
- [ ] えらいボタン機能
- [ ] 捨てたボタン機能
- [ ] LINE通知リマインド機能

## 必要なページ
- [ ] トップページ
- [ ] ログインページ
- [ ] マイページ
- [ ] 投稿一覧ページ
- [ ] 投稿作成ページ
- [ ] 投稿編集・削除ページ
- [ ] お問い合わせ
- [ ] 利用規約
- [ ] プライバシーポリシー

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下、コメントになります。
--- 
- ストーリポイントが 5 になっているissueは 2~3 に 分解できないかもう一度確認してみましょう。
- いくつかのissueに「機能作成」「view」の二つのタスクがあるかと思うので、各々で1つのissueにしてもいいように思いました。

**Comment by fumi-328** [comment]
回答ありがとうございます。

ストーリポイントが 5 になっているissueは 2~3 に 分解し、
タスクの分散を行いました。

よろしくお願いいたします。

**Comment by kenchasonakai** [comment]
LGTMです！
