### ISSUE TITLE
MVPリリース・レビュー依頼

### ISSUE THREAD

**Issue by fumi-328** [fumi-328/danshari#31]

**Comment by fumi-328** [comment]
## 各種情報
サービス名:断捨離memo
サービスURL:https://dansharimemo-3966376e7aab.herokuapp.com


## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] LINEログイン機能
- [ ] ログアウト機能
- [ ] LINE通知機能
- [ ] 検索機能
- [ ] ユーザー全員の物一覧閲覧機能（未ログインでも閲覧可能）
- [ ] 断捨離する物の投稿機能（画像投稿含む,詳細の登録）
- [ ] 断捨離する物の編集機能
- [ ] 断捨離する物の削除機能
- [ ] えらいボタン機能
- [ ] 捨てたボタン機能
- [ ] トップページ
- [ ] マイページ(総えらい数・捨てた総数の掲載)
- [ ] お問合せ
- [ ] 利用規約
- [ ] プライバシーポリシー

## READMEレビュー時から変更した機能
機能の変更ではないですが、テーブルの変更がありました。
・LINEログイン機能の為、AuthenticationsテーブルとUsersテーブルを一対一で関連付けを行う予定だったが、
Usersテーブルに統合し[uid/provier]を追加。。
・LINE通知機能の設定の際、Usersテーブルに[line_alert]を追加。
[![Image from Gyazo](https://i.gyazo.com/2ac5413db6eecaa5030a5442fec9d18b.png)](https://gyazo.com/2ac5413db6eecaa5030a5442fec9d18b)

## サービスイメージがわかるようなスクリーンショット等
### LINEログイン
[![Image from Gyazo](https://i.gyazo.com/d3b519fd84c4bebbe90a6d31f287da90.gif)](https://gyazo.com/d3b519fd84c4bebbe90a6d31f287da90)

### マイページ
[![Image from Gyazo](https://i.gyazo.com/8d6162c30ddfb435b1309927cc318256.png)](https://gyazo.com/8d6162c30ddfb435b1309927cc318256)

### LINE通知機能
Heroku Scheduler
[![Image from Gyazo](https://i.gyazo.com/fc90dccc0aee2960a2fb104a4fcb101b.png)](https://gyazo.com/fc90dccc0aee2960a2fb104a4fcb101b)

LINE上での通知画面
[![Image from Gyazo](https://i.gyazo.com/10086e2cc60eb055fa6f5cfe37562378.png)](https://gyazo.com/10086e2cc60eb055fa6f5cfe37562378)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
